code: "sample"
version: "1.1.0"
title: "Sample"
oneliner: "DO NOT copy from this module to create new one, use boilerplateStart instead. Developer use this module to test the completeness of module architecture."
lastUpdate: "2019-09-19"
developer:
  author: "Tan Yee Siang"
  organization: "MaGIC"
  email: "yee.siang@mymagic.my"
dependency:
  - module: 'boilerplateStart'
    version: '1.0'