code: "service"
version: "1.0"
title: "Services"
oneliner: "List out all the services offered by MaGIC"
lastUpdate: "2019-17-12"
developer:
  author: "Rosaan Ramasamy"
  organization: "MaGIC"
  email: "rosaan@mymagic.my"