url: "https://mymagic.github.io/open_hub" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Open Hub" # the name of your site, e.g. ACME Corp.
name: "Open Hub"